version: '3'
services:
  database:
    container_name: consulgest-db
    image: postgres:latest
    environment:
      POSTGRES_DB: "${DATABASE_DBNAME:-consulgest}"
      POSTGRES_USER: "${DATABASE_USER:-consulgest}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD:-consulgest}"
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "${EXTERNAL_DB_PORT:-5432}:5432"
    networks:
      - mynet
  api:
    container_name: consulgest-api
    build:
      context: ../
      dockerfile: _docker/python/Dockerfile
    entrypoint: "bash -c 'python manage.py makemigrations && python manage.py migrate && python manage.py migrate --run-syncdb && python manage.py runserver 0.0.0.0:8000'"
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
    volumes:
      - ../:/usr/src/app
    networks:
      - mynet
  nginx:
    container_name: consulgest-nginx
    build:
      context: ./nginx
    volumes:
      - '..:/usr/src/app'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/sites/:/etc/nginx/sites-available'
      - './nginx/conf.d/:/etc/nginx/conf.d'
      - './nginx/logs:/var/log/nginx'
    depends_on:
      - api
    ports:
      - '${EXTERNAL_HTTP_PORT:-80}:80'
      - '${EXTERNAL_HTTPS_PORT:-443}:443'
    networks:
      - mynet  

networks:
  mynet:
   driver: bridge

volumes:
  database:
   driver: local